name: Build firmware

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: martinfger/iot_devel:1.0

    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          cd esp_wifi_repeater
          make
